//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------


namespace Demo.Services.Entities
{
    public partial class BusinessObject
    {
        public BusinessObject()
        {
        }

        #region Properties

        public int Id  { get; set; }

        public string Stub  { get; set; }

        public string Description  { get; set; }

        public bool? Active  { get; set; }

        #endregion
    }
}