//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Demo.Services.Entities
{
    public class BusinessObjectTypeConfig : IEntityTypeConfiguration<BusinessObjectType>
    {
        public void Configure(EntityTypeBuilder<BusinessObjectType> c)
        {
            c.ToTable("BusinessObjectType")
             .HasKey(e => e.Id);

            // configure relationships

            c.HasOne(e => e.BusinessObjectObject)
             .WithMany()
             .HasForeignKey(e => e.BusinessObject);

            // configure properties
          
            c.Property(e => e.Id)
             .HasColumnName("Id")
             .HasColumnType("int")
             .IsRequired()
             .ValueGeneratedOnAdd();

            c.Property(e => e.BusinessObject)
             .HasColumnName("BusinessObject")
             .HasColumnType("int")
             .IsRequired();

            c.Property(e => e.Stub)
             .HasColumnName("Stub")
             .HasColumnType("varchar")
             .HasMaxLength(30);

            c.Property(e => e.Description)
             .HasColumnName("Description")
             .HasColumnType("varchar")
             .HasMaxLength(255);

            c.Property(e => e.Active)
             .HasColumnName("Active")
             .HasColumnType("bit");

        }
    }
}