//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------
using Microsoft.EntityFrameworkCore;

namespace Demo.Services.Entities
{
    public partial class DemoEntities : DbContext
    {
        public DemoEntities(DbContextOptions options) : base(options)
        {
        }

        #region Entities

        public virtual DbSet<BusinessObject> BusinessObject { get; set; }

        public virtual DbSet<BusinessObjectType> BusinessObjectType { get; set; }

        public virtual DbSet<MaintenanceTemplate> MaintenanceTemplate { get; set; }

        #endregion

        #region Configurations

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new BusinessObjectConfig());
            modelBuilder.ApplyConfiguration(new BusinessObjectTypeConfig());
            modelBuilder.ApplyConfiguration(new MaintenanceTemplateConfig());
        }

        #endregion
    }
}