//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------


namespace Demo.Services.Entities
{
    public partial class MaintenanceTemplate
    {
        public MaintenanceTemplate()
        {
        }

        #region Properties

        public int Id  { get; set; }

        public string Stub  { get; set; }

        public string Description  { get; set; }

        public int ScheduleType  { get; set; }

        public int WorkOrderType  { get; set; }

        public int? Duration  { get; set; }

        public bool? Active  { get; set; }

        #endregion

        #region Navigation Properties

        ///<summary>
        /// BusinessObjectType object referenced by the field ScheduleType.
        ///</summary>
        public virtual BusinessObjectType ScheduleTypeObject { get; set; }

        ///<summary>
        /// BusinessObjectType object referenced by the field WorkOrderType.
        ///</summary>
        public virtual BusinessObjectType WorkOrderTypeObject { get; set; }

        #endregion
    }
}