//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Demo.Services.Entities
{
    public class MaintenanceTemplateConfig : IEntityTypeConfiguration<MaintenanceTemplate>
    {
        public void Configure(EntityTypeBuilder<MaintenanceTemplate> c)
        {
            c.ToTable("MaintenanceTemplate")
             .HasKey(e => e.Id);

            // configure relationships

            c.HasOne(e => e.ScheduleTypeObject)
             .WithMany()
             .HasForeignKey(e => e.ScheduleType);

            c.HasOne(e => e.WorkOrderTypeObject)
             .WithMany()
             .HasForeignKey(e => e.WorkOrderType);

            // configure properties
          
            c.Property(e => e.Id)
             .HasColumnName("Id")
             .HasColumnType("int")
             .IsRequired()
             .ValueGeneratedOnAdd();

            c.Property(e => e.Stub)
             .HasColumnName("Stub")
             .HasColumnType("varchar")
             .HasMaxLength(30);

            c.Property(e => e.Description)
             .HasColumnName("Description")
             .HasColumnType("varchar")
             .HasMaxLength(255);

            c.Property(e => e.ScheduleType)
             .HasColumnName("ScheduleType")
             .HasColumnType("int")
             .IsRequired();

            c.Property(e => e.WorkOrderType)
             .HasColumnName("WorkOrderType")
             .HasColumnType("int")
             .IsRequired();

            c.Property(e => e.Duration)
             .HasColumnName("Duration")
             .HasColumnType("int");

            c.Property(e => e.Active)
             .HasColumnName("Active")
             .HasColumnType("bit");

        }
    }
}