//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Service Implementations" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated
// unless they are placed between corresponding CUSTOM_CODE_START/CUSTOM_CODE_END lines.
//
// This file can be DELETED DURING REGENERATION IF NO LONGER NEEDED, e.g. if it gets renamed.
// To prevent this and preserve manual custom changes please remove the line above.
//---------------------------------------------------------------------------------------------

using Demo.Services.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Xomega.Framework.Services;
// CUSTOM_CODE_START: add namespaces for custom code below
// CUSTOM_CODE_END

namespace Demo.Services.Entities
{
    public partial class BusinessObjectTypeService : BaseService, IBusinessObjectTypeService
    {
        protected DemoEntities ctx;

        public BusinessObjectTypeService(IServiceProvider serviceProvider) : base(serviceProvider)
        {
            ctx = serviceProvider.GetService<DemoEntities>();
        }

        public virtual async Task<Output<ICollection<BusinessObjectType_ReadEnumsOutput>>> ReadEnumsAsync(CancellationToken token = default)
        {
            ICollection<BusinessObjectType_ReadEnumsOutput> res = null;
            try
            {
                currentErrors.AbortIfHasErrors();

                // CUSTOM_CODE_START: add custom security checks for ReadEnums operation below
                // CUSTOM_CODE_END
                var src = from obj in ctx.BusinessObjectType select obj;

                // CUSTOM_CODE_START: add custom filter criteria to the source query for ReadEnums operation below
                // src = src.Where(o => o.FieldName == VALUE);
                // CUSTOM_CODE_END

                var qry = from obj in src
                          select new BusinessObjectType_ReadEnumsOutput() {
                              // CUSTOM_CODE_START: set the EnumType output parameter of ReadEnums operation below
                              EnumType = Common.Enumerations.BusinessObject.EnumName + obj.BusinessObject, // CUSTOM_CODE_END
                              Id = obj.Id,
                              Stub = obj.Stub,
                              Description = obj.Description,
                              Active = obj.Active,
                          };

                // CUSTOM_CODE_START: add custom filter criteria to the result query for ReadEnums operation below
                // qry = qry.Where(o => o.FieldName == VALUE);
                // CUSTOM_CODE_END

                currentErrors.AbortIfHasErrors();
                res = await qry.ToListAsync(token);
            }
            catch (Exception ex)
            {
                currentErrors.MergeWith(errorParser.FromException(ex));
            }
            return await Task.FromResult(new Output<ICollection<BusinessObjectType_ReadEnumsOutput>>(currentErrors, res));
        }
    }
}