//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Blazor Views" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System.Collections.Generic;
using Xomega.Framework.Blazor.Components;

namespace Demo.Client.Blazor.Common.Views
{
    public class MainMenu
    {
        public static List<MenuItem> Items = new List<MenuItem>()
        {
            new MenuItem()
            {
                ResourceKey = "Module_Views_NavMenu",
                IconClass = "bi bi-columns",
                Items = new List<MenuItem>()
                {
                    new MenuItem()
                    {
                        ResourceKey = "MaintenanceTemplateView_NavMenu",
                        IconClass = "bi bi-pencil-square",
                        Href = "MaintenanceTemplateView?_action=create"
                    },
                    new MenuItem()
                    {
                        ResourceKey = "MaintenanceTemplateListView_NavMenu",
                        IconClass = "bi bi-card-list",
                        Href = "MaintenanceTemplateListView"
                    },
                }
            },
        };
    }
}