//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Xomega.Framework.Services;

namespace Demo.Services.Common
{
    #region IBusinessObjectTypeService interface

    public interface IBusinessObjectTypeService
    {

        ///<summary>
        /// Reads a list of Business Object Type enums.
        ///</summary>
        Task<Output<ICollection<BusinessObjectType_ReadEnumsOutput>>> ReadEnumsAsync(CancellationToken token = default);

    }
    #endregion

    #region BusinessObjectType_ReadEnumsOutput structure

    ///<summary>
    /// The output structure of operation IBusinessObjectTypeService.ReadEnumsAsync.
    ///</summary>
    public class BusinessObjectType_ReadEnumsOutput
    {
        
        public string EnumType { get; set; }
        
        public int Id { get; set; }
        
        public string Stub { get; set; }
        
        public string Description { get; set; }
        
        public bool? Active { get; set; }
    }
    #endregion

}