//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Xomega Data Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Microsoft.Extensions.DependencyInjection;

namespace Demo.Client.Common.DataObjects
{
    public static class DataObjects
    {
        public static IServiceCollection AddDataObjects(this IServiceCollection services)
        {
            services.AddTransient<MaintenanceTemplateCriteria, MaintenanceTemplateCriteria>();
            services.AddTransient<MaintenanceTemplateList, MaintenanceTemplateList>();
            services.AddTransient<MaintenanceTemplateObject, MaintenanceTemplateObject>();
            return services;
        }
    }
}