//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Xomega Data Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Demo.Client.Common.DataProperties;
using Demo.Services.Common;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Threading;
using System.Threading.Tasks;
using Xomega.Framework;
using Xomega.Framework.Lookup;
using Xomega.Framework.Properties;
using Xomega.Framework.Services;

namespace Demo.Client.Common.DataObjects
{
    public partial class MaintenanceTemplateObject : DataObject
    {
        #region Constants

        public const string Active = "Active";
        public const string Description = "Description";
        public const string Duration = "Duration";
        public const string Id = "Id";
        public const string ScheduleType = "ScheduleType";
        public const string Stub = "Stub";
        public const string WorkOrderType = "WorkOrderType";

        #endregion

        #region Properties

        public EnumBoolProperty ActiveProperty { get; private set; }
        public TextProperty DescriptionProperty { get; private set; }
        public IntegerProperty DurationProperty { get; private set; }
        public IntegerKeyProperty IdProperty { get; private set; }
        public ScheduleTypeProperty ScheduleTypeProperty { get; private set; }
        public TextProperty StubProperty { get; private set; }
        public WorkOrderTypeProperty WorkOrderTypeProperty { get; private set; }

        #endregion

        #region Construction

        public MaintenanceTemplateObject()
        {
        }

        public MaintenanceTemplateObject(IServiceProvider serviceProvider) : base(serviceProvider)
        {
        }

        protected override void Initialize()
        {
            IdProperty = new IntegerKeyProperty(this, Id)
            {
                Required = true,
                Editable = false,
                IsKey = true,
            };
            StubProperty = new TextProperty(this, Stub)
            {
                Size = 30,
            };
            DescriptionProperty = new TextProperty(this, Description)
            {
                Size = 255,
            };
            ScheduleTypeProperty = new ScheduleTypeProperty(this, ScheduleType)
            {
                Required = true,
            };
            WorkOrderTypeProperty = new WorkOrderTypeProperty(this, WorkOrderType)
            {
                Required = true,
            };
            DurationProperty = new IntegerProperty(this, Duration)
            {
            };
            ActiveProperty = new EnumBoolProperty(this, Active)
            {
                EnumType = "yesno",
                LookupValidation = LookupValidationType.None,
            };
        }

        #endregion

        #region CRUD Operations

        protected override async Task<ErrorList> DoReadAsync(object options, CancellationToken token = default)
        {
            var output = await MaintenanceTemplate_ReadAsync(options, token);
            return output.Messages;
        }

        protected override async Task<ErrorList> DoSaveAsync(object options, CancellationToken token = default)
        {
            if (IsNew)
            {
                var output = await MaintenanceTemplate_CreateAsync(options, token);
                return output.Messages;
            }
            else
            {
                var output = await MaintenanceTemplate_UpdateAsync(options, token);
                return output.Messages;
            }
        }

        protected override async Task<ErrorList> DoDeleteAsync(object options, CancellationToken token = default)
        {
            var output = await MaintenanceTemplate_DeleteAsync(options, token);
            return output.Messages;
        }

        #endregion

        #region Service Operations

        protected virtual async Task<Output<MaintenanceTemplate_ReadOutput>> MaintenanceTemplate_ReadAsync(object options, CancellationToken token = default)
        {
            int _id = (int)IdProperty.TransportValue;
            using (var s = ServiceProvider.CreateScope())
            {
                var output = await s.ServiceProvider.GetService<IMaintenanceTemplateService>().ReadAsync(_id, token);

                await FromDataContractAsync(output?.Result, options, token);
                return output;
            }
        }

        protected virtual async Task<Output<MaintenanceTemplate_CreateOutput>> MaintenanceTemplate_CreateAsync(object options, CancellationToken token = default)
        {
            MaintenanceTemplate_CreateInput _data = ToDataContract<MaintenanceTemplate_CreateInput>(options);
            using (var s = ServiceProvider.CreateScope())
            {
                var output = await s.ServiceProvider.GetService<IMaintenanceTemplateService>().CreateAsync(_data, token);

                await FromDataContractAsync(output?.Result, options, token);
                return output;
            }
        }

        protected virtual async Task<Output> MaintenanceTemplate_UpdateAsync(object options, CancellationToken token = default)
        {
            int _id = (int)IdProperty.TransportValue;
            MaintenanceTemplate_UpdateInput_Data _data = ToDataContract<MaintenanceTemplate_UpdateInput_Data>(options);
            using (var s = ServiceProvider.CreateScope())
            {
                var output = await s.ServiceProvider.GetService<IMaintenanceTemplateService>().UpdateAsync(_id, _data, token);

                return output;
            }
        }

        protected virtual async Task<Output> MaintenanceTemplate_DeleteAsync(object options, CancellationToken token = default)
        {
            int _id = (int)IdProperty.TransportValue;
            using (var s = ServiceProvider.CreateScope())
            {
                var output = await s.ServiceProvider.GetService<IMaintenanceTemplateService>().DeleteAsync(_id, token);

                return output;
            }
        }

        #endregion
    }
}