//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Label Resources" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;
using System.Resources;

namespace Demo.Client.Common
{
    public static class Labels
    {
        private static readonly Lazy<ResourceManager> resourceManager =
            new Lazy<ResourceManager>(() => new ResourceManager("Demo.Client.Common.Labels", typeof(Labels).Assembly));

        public static ResourceManager ResourceManager => resourceManager.Value;
    }
}